firewithinfilms/user/forms.py
from ast import Pass
from io import StringIO
from wsgiref.validate import validator
from flask_wtf import FlaskForm
from flask_wtf.file import FileField
from flask_wtf.file import FileAllowed
from flask_login import current_user
from flask_ckeditor import CKEditorField
from wtforms import StringField
from wtforms import PasswordField
from wtforms import SubmitField
from wtforms import BooleanField
from wtforms import TextAreaField
from wtforms import SelectField
from wtforms.validators import DataRequired
from wtforms.validators import Length
from wtforms.validators import Email
from wtforms.validators import EqualTo
from wtforms.validators import ValidationError
from firewithinfilms.models import User


class RegistrationForm(FlaskForm):
    
    username = StringField(
        'Username',
        validators = [
            DataRequired(), 
            Length(min=2, max=20)
        ]
    )

    email = StringField(
        'Email',
        validators = [
            DataRequired(), 
            Email()
        ]
    )

    password = PasswordField(
        'Password', 
        validators = [ 
            DataRequired()
        ]
    )
    
    confirm_password = PasswordField(
        'Confirm Password',
        validators = [
            DataRequired(), 
            EqualTo('password')
        ]
    )
    
    submit = SubmitField('Create account')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('That username is taken. Please choose a different one.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('That email is taken. Please choose a different one.')


class LoginForm(FlaskForm):
    email = StringField(
        'Email',
        validators = [
            DataRequired(), 
            Email()
        ]
    )

    password = PasswordField(
        'Password', 
        validators = [DataRequired()]
    )

    remember = BooleanField('Remember Me')

    submit = SubmitField('Login')
    

class UpdateAccountForm(FlaskForm):
    name = StringField(
        'Name',
        validators = [ 
            Length(min=2, max=50)
        ]
    )

    username = StringField(
        'Username',
        validators = [ 
            Length(min=2, max=20)
        ]
    )

    email = StringField(
        'Email',
        validators = [
            Email()
        ]
    )

    picture = FileField(
        'Update Profile Picture', 
        validators = [
            FileAllowed(['jpg','jpeg','png'])
        ]
    )

    submit = SubmitField('Save')

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError('That username is taken. Please choose a different one.')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('That email is taken. Please choose a different one.')


class UpdateAccountDescriptionForm(FlaskForm):
    description = TextAreaField(
        'Description',
        validators = [
            DataRequired()
        ]
    )

    primary_lang = SelectField(
        'Primary Language',
        choices = [
            ('N/A', '-- Select Language --' ),
            ('hindi', 'Hindi' ),
            ('english', 'English' ),
            ('bangla', 'Bangla' ),
        ],
        validators = [
            DataRequired()
        ]
    )

    secondary_lang = SelectField(
        'Secondary Language',
        choices = [
            ('N/A', '-- Select Language --' ),
            ('hindi', 'Hindi' ),
            ('english', 'English' ),
            ('bangla', 'Bangla' ),
        ],
        validators = [
            DataRequired()
        ]
    )

    skill_1 = SelectField(
        'Skill',
        choices = [
            ('N/A', '-- Select Skill --' ),
            ('singing', 'Singing' ),
            ('dancing', 'Dancing' ),
            ('voice artist', 'Voice Artist' ),
            ('acting', 'Acting' ),
            ('script writing', 'Script Writing' ),
        ],
        validators = [
            DataRequired()
        ]
    )

    skill_2 = SelectField(
        'Another Skill',
        choices = [
            ('N/A', '-- Select Skill --' ),
            ('singing', 'Singing' ),
            ('dancing', 'Dancing' ),
            ('voice artist', 'Voice Artist' ),
            ('acting', 'Acting' ),
            ('script writing', 'Script Writing' ),
        ],
    )

    skill_3 = SelectField(
        'Another Skill',
        choices = [
            ('N/A', '-- Select Skill --' ),
            ('singing', 'Singing' ),
            ('dancing', 'Dancing' ),
            ('voice artist', 'Voice Artist' ),
            ('acting', 'Acting' ),
            ('script writing', 'Script Writing' ),
        ],
    )

    skill_4 = SelectField(
        'Another Skill',
        choices = [
            ('N/A', '-- Select Skill --' ),
            ('singing', 'Singing' ),
            ('dancing', 'Dancing' ),
            ('voice artist', 'Voice Artist' ),
            ('acting', 'Acting' ),
            ('script writing', 'Script Writing' ),
        ],
    )

    skill_5 = SelectField(
        'Another Skill',
        choices = [
            ('N/A', '-- Select Skill --' ),
            ('singing', 'Singing' ),
            ('dancing', 'Dancing' ),
            ('voice artist', 'Voice Artist' ),
            ('acting', 'Acting' ),
            ('script writing', 'Script Writing' ),
        ],
    )

    education_institue_name = StringField(
        'College/University Name',
    )

    education_graduation_name = StringField(
        'Course/Degree Name',
    )

    education_institue_country = StringField(
        'College/University Country',
    )

    education_graduation_year = StringField(
        'Graduated Year (Don\'t Fill up if your study is still running)'
    )

    submit = SubmitField('Update')


class PostForm(FlaskForm):
    title = StringField(
        'Title', 
        validators=[ DataRequired() ]
    )

    content = CKEditorField(
        'What is happening?', 
        validators=[ DataRequired() ]
    )
   
    picture = FileField(
        'Add a banner image', 
        validators = [
            FileAllowed(['jpg', 'jpeg', 'png'])
        ]
    )

    submit = SubmitField('Post')


class UpdatePasswordForm(FlaskForm):
    currentPassword = PasswordField(
        'Current Password', 
        validators=[ DataRequired() ]
    )

    newPassword = PasswordField(
        'New Password', 
        # validators=[ DataRequired() ]
    )

    confirmnewPassword = PasswordField(
        'Confirm New Password', 
        # validators=[ DataRequired() ]
    )

    submit = SubmitField('Save')


#   FORGET PASSWORD FORM
class ForgetPasswordForm(FlaskForm):
    email = StringField(
        'Email',
        validators = [
            Email()
        ]
    )

    submit = SubmitField('Send Reset Link')


#   CHANGE PASSWORD TOKEN
class ResetPasswordForm(FlaskForm):
    password = PasswordField(
            'Password',
            validators=[ DataRequired() ]
    )

    confirm_password = PasswordField(
            'Confirm Password',
            validators = [
                DataRequired(),
                EqualTo('password')
            ]
    )

    submit = SubmitField('Reset Password')

firewithinfilms/user/views.py
import os
import re
import secrets
from PIL import Image

from flask import render_template
from flask import url_for
from flask import flash
from flask import redirect
from flask import request
from flask import session
from flask import abort
from flask import current_app

from flask import Blueprint

from firewithinfilms import db
from firewithinfilms import bcrypt

from firewithinfilms.user.forms import RegistrationForm
from firewithinfilms.user.forms import LoginForm
from firewithinfilms.user.forms import UpdateAccountForm
from firewithinfilms.user.forms import UpdateAccountDescriptionForm
from firewithinfilms.user.forms import PostForm
from firewithinfilms.user.forms import UpdatePasswordForm
from firewithinfilms.user.forms import ForgetPasswordForm
from firewithinfilms.user.forms import ResetPasswordForm

from firewithinfilms.models import User
from firewithinfilms.models import UserPost
from firewithinfilms.models import UserDetails
from firewithinfilms.models import UserReviews

from flask_login import login_user
from flask_login import current_user
from flask_login import logout_user
from flask_login import login_required

from firewithinfilms.utils.location import getLocation

from firewithinfilms.utils.save_image import save_post_picture
from firewithinfilms.utils.save_image import save_profile_picture
from firewithinfilms.utils.send_email import send_reset_email


user = Blueprint('users', __name__)

production=True
# production=False

# USER PUBLIC PROFLE
@user.route('/<string:username>/')
def user_profile(username):
    user = User.query.filter_by(username=username).first_or_404()
    details = UserDetails.query.filter_by(user_id=user.id)
    posts = UserPost.query.filter_by(author=user).order_by(UserPost.date_posted.desc()).all()
    return render_template('public/publicaccount.html', user=user, details=details, posts=posts)

#   DASHBOARD FOR USER
@user.route('/user/dashboard/', methods=['GET', 'POST'])
@login_required
def user_dashboard():
    # posts = UserPost.query.all()
    posts = UserPost.query.order_by(UserPost.date_posted.desc()).all()
    user = User.query.filter_by(username=current_user.username).first_or_404()
    reviews = UserReviews.query.filter_by(user_id=user.id)
    details = UserDetails.query.filter_by(user_id=user.id)
    completed_account_descreption=False
    complete_account=False

    #   UPDATING COUNTRY
    if production is True:
        ip_request = request.remote_addr
    else:
        ip_request = '17.249.252.255'

    location = getLocation(ip_request)

    for detail in details:
        #   STORE LOCATION IN DATABASE
        detail.location = location[0]
        detail.country = location[1] 

        if detail.user_headline == 'N/A': 
            completed_account_descreption=False
            print('User headline is NA')
        else:
            completed_account_descreption=True
            print('User headline is GOOD')

        if detail.description == 'N/A':
            completed_account_descreption=False
            print('User description is NA')
        else:
            completed_account_descreption=True
            print('User description is GOOD')
        
        if detail.primary_lang == 'N/A':
            completed_account_descreption=False
            print('User primary_lang is NA')
        else:
            completed_account_descreption=True
            print('User primary_lang is GOOD')
        
        if detail.secondary_lang == 'N/A':
            completed_account_descreption=False
            print('User secondary_lang is NA')
        else:
            completed_account_descreption=True
            print('User secondary_lang is GOOD')
        
        if detail.skill_1 == 'N/A':
            completed_account_descreption=False
            print('User skill_1 is NA')
        else:
            completed_account_descreption=True
            print('User skill_1 is GOOD')
        
        if detail.skill_2 == 'N/A':
            completed_account_descreption=False
            print('User skill_2 is NA')
        else:
            completed_account_descreption=True
            print('User skill_2 is GOOD')
        
        if detail.skill_3 == 'N/A':
            completed_account_descreption=False
            print('User skill_3 is NA')
        else:
            completed_account_descreption=True
            print('User skill_3 is GOOD')
        
        if detail.skill_4 == 'N/A':
            completed_account_descreption=False
            print('User skill_4 is NA')
        else:
            completed_account_descreption=True
            print('User skill_4 is GOOD')
        
        if detail.skill_5 == 'N/A':
            completed_account_descreption=False
            print('User skill_5 is NA')
        else:
            completed_account_descreption=True
            print('User skill_5 is GOOD')
        
        if detail.education_institue_name == 'N/A':
            completed_account_descreption=False
            print('User education_graduation_name is NA')
        else:
            completed_account_descreption=True
            print('User education_graduation_name is GOOD')
        
        if detail.education_graduation_name == 'N/A':
            completed_account_descreption=False
            print('User education_graduation_name is NA')
        else:
            completed_account_descreption=True
            print('User education_graduation_name is GOOD')
        
        if detail.education_institue_country == 'N/A':
            completed_account_descreption=False
            print('User education_institue_country is NA')
        else:
            completed_account_descreption=True
            print('User education_institue_country is GOOD')
        
        if user.name == None:
            print('name is none')
            complete_account=False   
        else:
            print('name is something')
            complete_account=True

    db.session.commit()

    return render_template('user/dashboard.html', posts=posts, completed_account_descreption=completed_account_descreption, 
                        complete_account=complete_account)

#   ACCOUNT PAGE FOR USERS
@user.route('/user/account/', methods=['GET', 'POST'])
@login_required
def user_account():
    if current_user.is_authenticated:
        user = User.query.filter_by(username=current_user.username).first_or_404()
        reviews = UserReviews.query.filter_by(user_id=user.id)
        details = UserDetails.query.filter_by(user_id=user.id)

        review_1 = 0
        review_2 = 0
        review_3 = 0
        review_4 = 0
        review_5 = 0
        avg_review_counting = 0
        remainder=0
        null_review = True

        # counting review
        for review in reviews:
            print('-------------')
            print(f'Review---->>> {review.star}')
            if review.star != '0':
                avg_review_counting = avg_review_counting+int(review.star)
                remainder += 1
                null_review = False
        
            if review.star == '5':
                review_5 = review_5 + 1
            elif review.star == '4':
                review_4 = review_4 + 1
            elif review.star == '3':
                review_3 = review_3 + 1
            elif review.star == '2':
                review_2 = review_2 + 1
            elif review.star == '1':
                review_1 = review_1 + 1
            else:
                null_review=True

        # average review
        if null_review == True:
            avg_review=0
        else:
            avg_review = avg_review_counting/remainder
    

        # checking if the user profile is complete
        for detail in details:
            if detail.user_headline == 'N/A': 
                completed_account_descreption=False
                print('User headline is NA')
            else:
                completed_account_descreption=True
                print('User headline is GOOD')

            if detail.description == 'N/A':
                completed_account_descreption=False
                print('User description is NA')
            else:
                completed_account_descreption=True
                print('User description is GOOD')
            
            if detail.primary_lang == 'N/A':
                completed_account_descreption=False
                print('User primary_lang is NA')
            else:
                completed_account_descreption=True
                print('User primary_lang is GOOD')
            
            if detail.secondary_lang == 'N/A':
                completed_account_descreption=False
                print('User secondary_lang is NA')
            else:
                completed_account_descreption=True
                print('User secondary_lang is GOOD')
            
            if detail.skill_1 == 'N/A':
                completed_account_descreption=False
                print('User skill_1 is NA')
            else:
                completed_account_descreption=True
                print('User skill_1 is GOOD')
            
            if detail.skill_2 == 'N/A':
                completed_account_descreption=False
                print('User skill_2 is NA')
            else:
                completed_account_descreption=True
                print('User skill_2 is GOOD')
            
            if detail.skill_3 == 'N/A':
                completed_account_descreption=False
                print('User skill_3 is NA')
            else:
                completed_account_descreption=True
                print('User skill_3 is GOOD')
            
            if detail.skill_4 == 'N/A':
                completed_account_descreption=False
                print('User skill_4 is NA')
            else:
                completed_account_descreption=True
                print('User skill_4 is GOOD')
            
            if detail.skill_5 == 'N/A':
                completed_account_descreption=False
                print('User skill_5 is NA')
            else:

firewithinfilms/templates/user/change_password.html
{% extends 'root-dashboard.html' %}

<!--  -->
{% block head %}
<link
	rel="stylesheet"
	href="{{ url_for('static', filename='assets/scripts/login-signup.css') }}"
/>
{% endblock %}

<!--  -->
{% block content %}
	
<!--  -->
{% include 'helpers/_sidenav_dashboard.html' %}

<div class="px-1 pl-75">
	<form method="POST" action="" enctype="multipart/form-data">
		<div class="container">
			<div
				class="header-sm flex flex-j-space-between flex-a-center p-5"
			>
				<a
					href="{{ url_for('users.user_dashboard') }}"
					class="button button__sm button__second submit__button button__alt flex"
				>
					<i class="bx bx-left-arrow-alt h2-sm"></i>
					<p>Go Back</p>
				</a>
				<span>
					{{ form.submit(class="button button__sm submit__button")}}
				</span>
			</div>
		</div>
		

		<div
			class="container bg__primary-alt admin__panel-form-container my-1"
		>
			<div class="flex flex-j-start flex-a-center p-5">
				<img
					src="{{url_for('static', filename='profile_pics/' + current_user.image_file)}}"
					alt="{{current_user.name}} - FireWithinFilms"
					class="img__round-sm mx-1"
				/>
				<h2 class="h2-sm">{{current_user.name}}</h2>
			</div>

			{{ form.hidden_tag() }}

			<!-- current password -->
			{{ form.currentPassword.label(class="ml-5 text-bold") }} 
			
			{% if form.currentPassword.errors %}
			<div class="login__box-container login__box-lighter my-5 mb-75">
				<div class="login__box login__box-error">
					{{ form.currentPassword( 
						class="login__input login__input-error",
						placeholder="Current Password" 
					) }}
				</div>
				{% for error in form.currentPassword.errors %}
				<small class="error__message">{{ error }}</small>
				{% endfor %}
			</div>
			{% else %}
			<div class="login__box login__box-lighter my-5 mb-75">
				{{ form.currentPassword(
					class="login__input", 
					placeholder="Current Password"
				) }}
			</div>
			{% endif %}

            <!-- new password -->
			{{ form.newPassword.label(class="ml-5 text-bold") }} 
			
			{% if form.newPassword.errors %}
			<div class="login__box-container login__box-lighter my-5 mb-75">
				<div class="login__box login__box-error">
					{{ form.newPassword( 
						class="login__input login__input-error",
						placeholder="New Password" 
					) }}
				</div>
				{% for error in form.newPassword.errors %}
				<small class="error__message">{{ error }}</small>
				{% endfor %}
			</div>
			{% else %}
			<div class="login__box login__box-lighter my-5 mb-75">
				{{ form.newPassword(
					class="login__input", 
					placeholder="New Password"
				) }}
			</div>
			{% endif %}


            <!-- confirm new password -->
			{{ form.confirmnewPassword.label(class="ml-5 text-bold") }} 
			
			{% if form.confirmnewPassword.errors %}
			<div class="login__box-container login__box-lighter my-5 mb-75">
				<div class="login__box login__box-error">
					{{ form.confirmnewPassword( 
						class="login__input login__input-error",
						placeholder="Confirm New Password" 
					) }}
				</div>
				{% for error in form.confirmnewPassword.errors %}
				<small class="error__message">{{ error }}</small>
				{% endfor %}
			</div>
			{% else %}
			<div class="login__box login__box-lighter my-5 mb-75">
				{{ form.confirmnewPassword(
					class="login__input", 
					placeholder="Confirm New Password"
				) }}
			</div>
			{% endif %}

			<div style="display: flex; align-items: center;">
				<input type="checkbox" name="showpass" id="showpass" style="width: auto; height: 20px; width: 20px; margin-right: 0.3rem;">
				Show Password
			</div>
        </div>

		<div style="float: right; margin-top: 1rem">
			{{ form.submit(class="button button__sm submit__button")}}
		</div>

	</form>
</div>


<script>
	const checkshowpass = document.querySelector('#showpass');
	const currentpass = document.querySelector('#currentPassword'); 
	const newpass = document.querySelector('#newPassword');
	checkshowpass.addEventListener('click', ()=> {
		if (currentpass.type === "password" || newpass.type === "password") {
			currentpass.type = "text";
			newpass.type = "text";
		} else {
			currentpass.type = "password";
			newpass.type = "password";
		}
	});
</script>
{% endblock content %}

firewithinfilms/templates/user/createpost.html
{% extends 'root-dashboard.html' %}

<!--  -->
{% block head %}
<link
	rel="stylesheet"
	href="{{ url_for('static', filename='assets/scripts/login-signup.css') }}"
/>
{% endblock %}

<!--  -->
{% block content %}
	
<!--  -->
{% include 'helpers/_sidenav_dashboard.html' %}

<div class="px-1 pl-75">
	<form method="POST" action="" enctype="multipart/form-data">
		<div class="container">
			<div
				class="header-sm flex flex-j-space-between flex-a-center p-5"
			>
				<a
					href="{{ url_for('users.user_dashboard') }}"
					class="button button__sm button__second submit__button button__alt flex"
				>
					<i class="bx bx-left-arrow-alt h2-sm"></i>
					<p>Go Back</p>
				</a>
				<span>
					{{ form.submit(class="button button__sm submit__button")}}
				</span>
			</div>
		</div>
		

		<div
			class="container bg__primary-alt admin__panel-form-container my-1"
		>
			<div class="flex flex-j-start flex-a-center p-5">
				<img
					src="{{url_for('static', filename='profile_pics/' + current_user.image_file)}}"
					alt="{{current_user.name}} - FireWithinFilms"
					class="img__round-sm mx-1"
				/>
				<h2 class="h2-sm">Create Post</h2>
			</div>

			{{ form.hidden_tag() }}

			<!-- post title -->
			{{ form.title.label(class="ml-5 text-bold") }} 
			
			{% if form.title.errors %}
			<div class="login__box-container login__box-lighter my-5 mb-75">
				<div class="login__box login__box-error">
					{{ form.title( 
						class="login__input login__input-error",
						placeholder="Post Title" 
					) }}
				</div>
				{% for error in form.title.errors %}
				<small class="error__message">{{ error }}</small>
				{% endfor %}
			</div>
			{% else %}
			<div class="login__box login__box-lighter my-5 mb-75">
				{{ form.title(
					class="login__input", 
					placeholder="Post Title"
				) }}
			</div>
			{% endif %}

			<!-- post content -->
			{{ form.content.label(class="ml-5 text-bold") }} 
			
			{% if form.content.errors %}
			<div class="login__box-container login__box-lighter my-5 mb-75">
				<div class="login__box login__box-error">
					{{ form.content( 
						class="login__input login__details login__input-error",
						placeholder="Write your thoughts...",
						rows="10"
					) }}
				</div>
				{% for error in form.content.errors %}
				<small class="error__message">{{ error }}</small>
				{% endfor %}
			</div>
			{% else %}
			<div class="login__box login__box-lighter my-5 mb-75">
				{{ form.content( 
					class="login__input login__details",
					placeholder="Write your thoughts...",
					rows="10" 
				) }}
			</div>
			{% endif %}

			<!-- post banner -->
			{{ form.picture.label(class="ml-5 text-bold") }} 
			
			{% if form.picture.errors %}
			<div class="login__box-container login__box-lighter my-5 mb-75">
				<div class="login__box login__box-error">
					{{ form.picture( 
						class="login__input login__input-error",
						placeholder="Add banner image" 
					)}}
				</div>
				{% for error in form.picture.errors %}
				<small class="error__message">{{ error }}</small>
				{% endfor %}
			</div>
			{% else %}
			<div class="login__box login__box-lighter my-5 mb-75">
				{{ form.picture(
					class="login__input", 
					placeholder="Add banner image"
				) }}
			</div>
			{% endif %}
			
		</div>

		<div style="float: right; margin-top: 1rem">
			{{ form.submit(class="button button__sm submit__button")}}
		</div>

	</form>

	{{ ckeditor.load() }}
 	{{ ckeditor.config(name='content') }}
</div>

{% endblock content %}

firewithinfilms/templates/user/dashboard.html
{% extends 'root-dashboard.html' %}

<!--  -->
{% block head %}
<link
	rel="stylesheet"
	href="{{ url_for('static', filename='assets/scripts/reuse.css') }}"
/>
{% endblock %}

<!--  -->
{% block content %}

<!-- main content -->
{% if current_user.user_role != 'admin' %}
	<!-- complete your profile -->
	{% if complete_account != True %}
	<div class="alert alert__info">
		You account is incomplete.
		<a href="{{ url_for('users.user_edit_account') }}" class="link">
			Let's complete your profile first
		</a>
		and ROCK it 😎
	</div>
	{% elif completed_account_descreption != True %}
	<div class="alert alert__info">
		Impressive 😍 {{ current_user.name }}. One last step,
		<a href="{{ url_for('users.user_edit_description') }}" class="link">
			Let's complete your profile description
		</a>
		😎
	</div>
	{% endif %} 
    
{% endif %}

<div class="px-2 pl-75">
	{% include 'helpers/_sidenav_dashboard.html' %}

	<div
		class="section header-sm flex flex-j-space-between flex-a-center p-5"
	>
		<div class="flex flex-j-start flex-a-center">
			<img
				src="{{url_for('static', filename='profile_pics/' + current_user.image_file)}}"
				alt="{{current_user.name}} - FireWithinFilms"
				class="img__round-sm mx-1"
			/>
			<h2 class="h2-sm">Home</h2>
		</div>
	</div>

	<!-- post list -->
	{% if posts %}
	<h1 class="text__lighter h2-sm ml-75">Recent Posts</h1>
	
	{% for post in posts %}
	<article class="media content-section my-1 mx-5 ml-5 px-75 pl-75">
			<div class="container article__header flex pt-5">
				<img
					class="img__round-sm"
					src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}"
				/>

				<div class="article-metadata pl-1" style="margin-top: auto; margin-bottom: auto;">
					<a class="h3-sm mr-2 d-block" href="{{ url_for('users.user_profile', username=post.author.username) }}">
						{{ post.author.name }}
					</a>
					<small>
						{{ post.date_posted.strftime('%d %b, %Y') }}
					</small>
				</div>
			</div>

			<div class="container media-body pt-5 pb-5">
				<div>
					<a href="{{ url_for('users.user_post', post_id=post.id) }}">
						<h2 class="article__title">
							{{ post.title }}
						</h2>

						<p class="article-content">
							{{ post.content | truncate(200) | safe }}
						</p>
					</a>
				</div>
			</div>

	</article>
	{% endfor %} 

	{% else %}
	<h1>No post created yet</h1>
	{% endif %}
</div>
<!-- finish -->
{% endblock content %}

firewithinfilms/templates/user/forgetpassword.html
{% extends 'root.html' %}

<!-- additional links -->
{% block head %}
<link
	rel="stylesheet"
	href="{{ url_for('static', filename='assets/scripts/login-signup.css') }}"
/>
{% endblock %}

<!-- block content -->
{% block content %}

<!-- login page -->
<main class="center__center bg__primary">
	<section class="login__forms">
		<h1 class="login__title text__center">FireWithinFilms</h1>

		<form method="POST" action="" class="login__register" id="login-in">
			{{ form.hidden_tag() }}
			<h3>Forget your password?</h3>

			<!-- email -->
			{% if form.email.errors %}
			<div class="login__box-container">
				<div
					class="login__box login__box-icon-container login__box-error"
				>
					<!-- <i class="bx bx-user login__icon login__icon-error"></i> -->
					{{ form.email( class="login__input
					login__input-error",placeholder="E-mail" )}}
				</div>
				{% for error in form.email.errors %}
				<small class="error__message">{{ error }}</small>
				{% endfor %}
			</div>
			{% else %}
			<div class="login__box login__box-icon-container">
				<!-- <i class="bx bx-user login__icon"></i>                 -->
				{{ form.email(class="login__input", placeholder="E-mail") }}
			</div>
			{% endif %}

			{{ form.submit(class="button__lg bold mxy-2") }}

			<div class="text__dark">
				<span class="text__small-bold">Go back to</span>
				<span class="link bold" id="sign-up">
					<a class="link" href="{{ url_for('users.user_login') }}">
						Login
					</a>
				</span>
			</div>
		</form>
	</section>
</main>
{% endblock content %}

firewithinfilms/templates/user/inbox.html
{% extends 'root-dashboard.html' %}

<!--  -->
{% block content %}
	
<!--  -->
{% include 'helpers/_sidenav_dashboard.html' %}

<div class="container">

</div>

<div class="px-1 pl-75">
    <h1>Comming soon</h1>
</div>
{% endblock %}

firewithinfilms/templates/user/post_old.html
{% extends 'root.html' %} 

{% block content %}


<article class="media content-section">
	<img
		class="rounded-circle article-img"
		src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}"
		height="125"
		width="125"
	/>
	<div class="media-body">
		<div class="article-metadata">
			<a class="mr-2" href="{{ url_for('users.user_profile', username=current_user.username) }}">
				{{ post.author.username }}
			</a>
			<small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small
			>
			<h1>username: {{ current_user.username }}</h1>
			{% if post.author == current_user %}
			<div>
				<a
					class="btn btn-secondary btn-sm mt-1 mb-1"
					href="{{ url_for('users.user_update_post', post_id=post.id) }}"
					>Update</a
				>
				<form
					action="{{ url_for('users.user_delete_post', post_id=post.id) }}"
					method="POST"
				>
					<input
						class="btn btn-danger"
						type="submit"
						value="Delete"
					/>
				</form>
			</div>
			{% endif %}
		</div>
		<img class="rounded-circle article-img" src="{{ image_file }}" />
		<h2 class="article-title">{{ post.title }}</h2>
		<p class="article-content">{{ post.content }}</p>
	</div>
</article>
{% endblock content %}