firewithinfilms/user/views.py
import os
import re
import secrets
from PIL import Image

from flask import render_template
from flask import url_for
from flask import flash
from flask import redirect
from flask import request
from flask import session
from flask import abort
from flask import current_app

from flask import Blueprint

from firewithinfilms import db
from firewithinfilms import bcrypt

from firewithinfilms.user.forms import RegistrationForm
from firewithinfilms.user.forms import LoginForm
from firewithinfilms.user.forms import UpdateAccountForm
from firewithinfilms.user.forms import UpdateAccountDescriptionForm
from firewithinfilms.user.forms import PostForm
from firewithinfilms.user.forms import UpdatePasswordForm
from firewithinfilms.user.forms import ForgetPasswordForm
from firewithinfilms.user.forms import ResetPasswordForm

from firewithinfilms.models import User
from firewithinfilms.models import UserPost
from firewithinfilms.models import UserDetails
from firewithinfilms.models import UserReviews

from flask_login import login_user
from flask_login import current_user
from flask_login import logout_user
from flask_login import login_required

from firewithinfilms.utils.location import getLocation

from firewithinfilms.utils.save_image import save_post_picture
from firewithinfilms.utils.save_image import save_profile_picture
from firewithinfilms.utils.send_email import send_reset_email


user = Blueprint('users', __name__)

production=True
# production=False

# USER PUBLIC PROFLE
@user.route('/<string:username>/')
def user_profile(username):
    user = User.query.filter_by(username=username).first_or_404()
    details = UserDetails.query.filter_by(user_id=user.id)
    posts = UserPost.query.filter_by(author=user).order_by(UserPost.date_posted.desc()).all()
    return render_template('public/publicaccount.html', user=user, details=details, posts=posts)

#   DASHBOARD FOR USER
@user.route('/user/dashboard/', methods=['GET', 'POST'])
@login_required
def user_dashboard():
    # posts = UserPost.query.all()
    posts = UserPost.query.order_by(UserPost.date_posted.desc()).all()
    user = User.query.filter_by(username=current_user.username).first_or_404()
    reviews = UserReviews.query.filter_by(user_id=user.id)
    details = UserDetails.query.filter_by(user_id=user.id)
    completed_account_descreption=False
    complete_account=False

    #   UPDATING COUNTRY
    if production is True:
        ip_request = request.remote_addr
    else:
        ip_request = '17.249.252.255'

    location = getLocation(ip_request)

    for detail in details:
        #   STORE LOCATION IN DATABASE
        detail.location = location[0]
        detail.country = location[1] 

        if detail.user_headline == 'N/A': 
            completed_account_descreption=False
            print('User headline is NA')
        else:
            completed_account_descreption=True
            print('User headline is GOOD')

        if detail.description == 'N/A':
            completed_account_descreption=False
            print('User description is NA')
        else:
            completed_account_descreption=True
            print('User description is GOOD')
        
        if detail.primary_lang == 'N/A':
            completed_account_descreption=False
            print('User primary_lang is NA')
        else:
            completed_account_descreption=True
            print('User primary_lang is GOOD')
        
        if detail.secondary_lang == 'N/A':
            completed_account_descreption=False
            print('User secondary_lang is NA')
        else:
            completed_account_descreption=True
            print('User secondary_lang is GOOD')
        
        if detail.skill_1 == 'N/A':
            completed_account_descreption=False
            print('User skill_1 is NA')
        else:
            completed_account_descreption=True
            print('User skill_1 is GOOD')
        
        if detail.skill_2 == 'N/A':
            completed_account_descreption=False
            print('User skill_2 is NA')
        else:
            completed_account_descreption=True
            print('User skill_2 is GOOD')
        
        if detail.skill_3 == 'N/A':
            completed_account_descreption=False
            print('User skill_3 is NA')
        else:
            completed_account_descreption=True
            print('User skill_3 is GOOD')
        
        if detail.skill_4 == 'N/A':
            completed_account_descreption=False
            print('User skill_4 is NA')
        else:
            completed_account_descreption=True
            print('User skill_4 is GOOD')
        
        if detail.skill_5 == 'N/A':
            completed_account_descreption=False
            print('User skill_5 is NA')
        else:
            completed_account_descreption=True
            print('User skill_5 is GOOD')
        
        if detail.education_institue_name == 'N/A':
            completed_account_descreption=False
            print('User education_graduation_name is NA')
        else:
            completed_account_descreption=True
            print('User education_graduation_name is GOOD')
        
        if detail.education_graduation_name == 'N/A':
            completed_account_descreption=False
            print('User education_graduation_name is NA')
        else:
            completed_account_descreption=True
            print('User education_graduation_name is GOOD')
        
        if detail.education_institue_country == 'N/A':
            completed_account_descreption=False
            print('User education_institue_country is NA')
        else:
            completed_account_descreption=True
            print('User education_institue_country is GOOD')
        
        if user.name == None:
            print('name is none')
            complete_account=False   
        else:
            print('name is something')
            complete_account=True

    db.session.commit()

    return render_template('user/dashboard.html', posts=posts, completed_account_descreption=completed_account_descreption, 
                        complete_account=complete_account)

#   ACCOUNT PAGE FOR USERS
@user.route('/user/account/', methods=['GET', 'POST'])
@login_required
def user_account():
    if current_user.is_authenticated:
        user = User.query.filter_by(username=current_user.username).first_or_404()
        reviews = UserReviews.query.filter_by(user_id=user.id)
        details = UserDetails.query.filter_by(user_id=user.id)

        review_1 = 0
        review_2 = 0
        review_3 = 0
        review_4 = 0
        review_5 = 0
        avg_review_counting = 0
        remainder=0
        null_review = True

        # counting review
        for review in reviews:
            print('-------------')
            print(f'Review---->>> {review.star}')
            if review.star != '0':
                avg_review_counting = avg_review_counting+int(review.star)
                remainder += 1
                null_review = False
        
            if review.star == '5':
                review_5 = review_5 + 1
            elif review.star == '4':
                review_4 = review_4 + 1
            elif review.star == '3':
                review_3 = review_3 + 1
            elif review.star == '2':
                review_2 = review_2 + 1
            elif review.star == '1':
                review_1 = review_1 + 1
            else:
                null_review=True

        # average review
        if null_review == True:
            avg_review=0
        else:
            avg_review = avg_review_counting/remainder
    

        # checking if the user profile is complete
        for detail in details:
            if detail.user_headline == 'N/A': 
                completed_account_descreption=False
                print('User headline is NA')
            else:
                completed_account_descreption=True
                print('User headline is GOOD')

            if detail.description == 'N/A':
                completed_account_descreption=False
                print('User description is NA')
            else:
                completed_account_descreption=True
                print('User description is GOOD')
            
            if detail.primary_lang == 'N/A':
                completed_account_descreption=False
                print('User primary_lang is NA')
            else:
                completed_account_descreption=True
                print('User primary_lang is GOOD')
            
            if detail.secondary_lang == 'N/A':
                completed_account_descreption=False
                print('User secondary_lang is NA')
            else:
                completed_account_descreption=True
                print('User secondary_lang is GOOD')
            
            if detail.skill_1 == 'N/A':
                completed_account_descreption=False
                print('User skill_1 is NA')
            else:
                completed_account_descreption=True
                print('User skill_1 is GOOD')
            
            if detail.skill_2 == 'N/A':
                completed_account_descreption=False
                print('User skill_2 is NA')
            else:
                completed_account_descreption=True
                print('User skill_2 is GOOD')
            
            if detail.skill_3 == 'N/A':
                completed_account_descreption=False
                print('User skill_3 is NA')
            else:
                completed_account_descreption=True
                print('User skill_3 is GOOD')
            
            if detail.skill_4 == 'N/A':
                completed_account_descreption=False
                print('User skill_4 is NA')
            else:
                completed_account_descreption=True
                print('User skill_4 is GOOD')
            
            if detail.skill_5 == 'N/A':
                completed_account_descreption=False
                print('User skill_5 is NA')
            else:

firewithinfilms/templates/helpers/_dashboard_footer.html
 <!-- =========== FOOTER ============= -->
<footer class="bg__primary-alt d-flex justify-content-center align-items-center">
    <div class="container">
        <div class="text-center py-3">
            <h2>FireWithinFilms</h2>
            <p> Unleash your inner power </p>

            <small class="d-flex py-4 justify-content-center">
                <a href="#" class="link pe-4"> 
                    Privacy Policy </a>
                <a href="#" class="link pe-4"> Terms of service </a>
                <a href="#" class="link"> Help and support </a>
            </small>
            
            <div class="">
                <p class="footer__copy" style="margin-top: 2rem !important;">
                    &copy; <span id="yearvalue">20xx</span> FireWithinFilms. Designed and
                    Maintained by
                    <a href="https://hossainfoysal.com" style="color: #00a8ff"> Hossain Foysal </a>.
                </p>
            </div>
        </div>
    </div>

    <script>
        const year = new Date();
        const gettheyear = year.getFullYear();
        const yearel = document.querySelector("#yearvalue");
        yearel.innerHTML = gettheyear;
    </script>
</footer>

firewithinfilms/templates/helpers/_post_nav.html
<nav class="navbar bg-light">
    <div class="container container-fluid">
        <a class="navbar-brand">FireWithinFilms</a>

        {% if current_user.is_authenticated %}
        <a href="{{ url_for('users.user_create_post') }}" class="btn btn-warning rounded-pill">
            Create Post
        </a>
        {% else %}
        <a href="{{ url_for('users.user_login') }}" class="btn btn-warning rounded-pill">
            Login
        </a>
        {% endif %}
    </div>
</nav>

firewithinfilms/templates/helpers/_sidenav_dashboard.html
<nav class="nav__menu">
	<ul class="nav__list">
		<li class="nav__item">
			<a href="{{ url_for('users.user_dashboard') }}" class="nav__link">
				<i class="bx bx-home-alt nav__icon"></i>
				<span class="nav__name">Home</span>
			</a>
		</li>

		<li class="nav__item">
			<a href="{{ url_for('users.user_inbox') }}" class="nav__link">
				<i class="bx bx-message-rounded-dots nav__icon"></i>
				<span class="nav__name">Inbox</span>
			</a>
		</li>

		<li class="nav__item">
			<a href="{{ url_for('users.user_create_post') }}" class="nav__link">
				<i class="bx bxs-edit nav__icon"></i>
				<span class="nav__name">Create Post</span>
			</a>
		</li>

		<li class="nav__item">
			<a href="{{ url_for('users.user_account') }}" class="nav__link">
				<i class="bx bx-user nav__icon"></i>
				<span class="nav__name">Profile</span>
			</a>
		</li>

		<!-- <li class="nav__item">
			<a href="{{ url_for('users.user_account') }}" class="nav__link">
				<i class="bx bx-book-alt nav__icon"></i>
				<span class="nav__name">Profile Description</span>
			</a>
		</li> -->

		<li class="nav__item">
			<a href="{{ url_for('users.user_resetpassword') }}" class="nav__link">
				<i class="bx bx-lock nav__icon"></i>
				<span class="nav__name">Change Password</span>
			</a>
		</li>

		<li class="nav__item">
			<a href="{{ url_for('users.user_logout') }}" class="nav__link active-link btn__red-alt">
				<i class="bx bx-log-out nav__icon"></i>
				<span class="nav__name">Logout</span>
			</a>
		</li>
	</ul>
</nav>